services:
  - type: web
    name: backend-ma
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8000"
    buildCommand: ""
    startCommand: >
      /app/.venv/bin/uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: "/health"
    plan: free # Cambiar a otro plan según las necesidades
