sonar.projectKey=Back-Color-Game
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_5bb183b1051ed8dfeaed4fbc586ec5bb2570a000

# COMANDO DE EJECUCION
# docker run --rm --network="host" -e SONAR_HOST_URL="http://localhost:9000" -e SONAR_TOKEN="sqp_5bb183b1051ed8dfeaed4fbc586ec5bb2570a000" -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli -X
